name: Test VS installs

on:
  workflow_dispatch:

jobs:
  install_test:
    name: Upload Release Assets
    runs-on: windows-latest
    steps:
      - name: Choco install VS
        run: choco install -y visualstudio2022buildtools --version=117.9.7.0 --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installChannelUri https://aka.ms/vs/17/release/180911598_-255012421/channel"
      - name: Start VS commandline and override path
        run: '& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Launch-VsDevShell.ps1" && echo $env:PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8'
      - name: Get MSVC version
        run: cl
